name: Run Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip intall --upgrade pip
        pip install -r requirements.txt
        pip install pytest yfinance scikit-learn pandas

    - name: Run tests
      run: |
        pytest tests/
